import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f3f4f6' },
  topBar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#111827',
  },
  topTitle: { color: '#fff', fontSize: 24, fontWeight: '800' },
  topSub: { color: '#d1d5db', fontSize: 13, marginTop: 2 },
  tabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 10,
    gap: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  tabBtn: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
  },
  tabBtnActive: { backgroundColor: '#111827' },
  tabBtnText: { color: '#111827', fontWeight: '700', fontSize: 13 },
  tabBtnTextActive: { color: '#fff' },
  content: { padding: 14, paddingBottom: 40 },
  card: {
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 10,
  },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 14 },
  statCard: {
    width: '47%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  statValue: { fontSize: 22, fontWeight: '800', color: '#111827' },
  statLabel: { fontSize: 13, color: '#6b7280', marginTop: 4 },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
    marginTop: 8,
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
  },
  inputMulti: { minHeight: 80, textAlignVertical: 'top' },
  button: {
    backgroundColor: '#111827',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  buttonText: { color: '#fff', fontWeight: '800' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 999,
    marginBottom: 8,
  },
  chipActive: { backgroundColor: '#111827', borderColor: '#111827' },
  chipText: { fontSize: 13, fontWeight: '700', color: '#111827' },
  chipTextActive: { color: '#fff' },
  listRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  selectedRow: {
    backgroundColor: '#eef2ff',
    borderRadius: 12,
    paddingHorizontal: 10,
  },
  listTitle: { fontSize: 14, fontWeight: '800', color: '#111827' },
  listMeta: { fontSize: 12, color: '#6b7280', marginTop: 3 },
  roomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 8,
  },
  itemCard: {
    backgroundColor: '#f9fafb',
    borderRadius: 14,
    padding: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  itemCardSoft: {
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    padding: 10,
    marginTop: 8,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smallAction: {
    backgroundColor: '#dbeafe',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
  },
  smallActionText: { color: '#1d4ed8', fontWeight: '800', fontSize: 12 },
  smallDanger: {
    backgroundColor: '#fee2e2',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
  },
  smallDangerText: { color: '#991b1b', fontWeight: '800', fontSize: 12 },
  toggle: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#fff',
    alignSelf: 'flex-start',
  },
  toggleActive: { backgroundColor: '#111827', borderColor: '#111827' },
  toggleText: { color: '#fff', fontWeight: '800' },
  groupTitle: { fontSize: 15, fontWeight: '800', color: '#111827', marginBottom: 8 },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    gap: 10,
  },
  infoLabel: { color: '#374151', fontSize: 14 },
  infoValue: { color: '#111827', fontSize: 14, fontWeight: '700' },
  strongText: { fontWeight: '800', fontSize: 15 },
  inlineField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  inlineLabel: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
    fontWeight: '700',
  },
  inlineInput: {
    width: 90,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#111827',
  },
  docPage: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    padding: 18,
    marginTop: 10,
  },
  docCompany: { fontSize: 22, fontWeight: '800', color: '#111827' },
  docHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111827',
    marginTop: 12,
  },
  docSection: {
    fontSize: 15,
    fontWeight: '800',
    color: '#111827',
    marginTop: 12,
    marginBottom: 4,
  },
  docSmall: { fontSize: 12, color: '#374151', marginBottom: 2 },
  docBody: { fontSize: 13, color: '#111827', lineHeight: 20 },
  docDivider: { height: 1, backgroundColor: '#d1d5db', marginVertical: 10 },
});

export default styles;
